# Generated by Django 5.1.5 on 2025-05-14 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0008_register_moc_model_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('division', models.CharField(default='O', max_length=10)),
                ('player_count', models.IntegerField(default=0)),
                ('successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rankings Update',
                'verbose_name_plural': 'Rankings Updates',
                'ordering': ['-timestamp'],
            },
        ),
    ]
