# Generated by Django 5.1.5 on 2025-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0010_update_tournament_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentarchetype',
            options={'ordering': ['tournament_category', 'name']},
        ),
    ]
