# Generated by Django 5.1.5 on 2025-05-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0011_alter_tournamentarchetype_options'),
        ('tournament_creator', '0011_notificationbackendsetting_and_more'),
    ]

    operations = [
    ]
