# Generated by Django 5.1.5 on 2025-05-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0012_merge_20250526_1516'),
        ('tournament_creator', '0012_tournamentchart_notify_by_email_and_more'),
    ]

    operations = [
    ]
