# Generated by Django 5.1.5 on 2025-09-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0013_add_manual_tiebreak_resolution'),
        ('tournament_creator', '0013_merge_20250528_0625'),
    ]

    operations = [
    ]
