# Generated by Django 5.1.5 on 2025-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0013_add_manual_tiebreak_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='automatic_wins',
            field=models.IntegerField(default=0),
        ),
    ]
