# Generated by Django 5.1.5 on 2025-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0014_add_automatic_wins_to_playerscore'),
        ('tournament_creator', '0014_merge_20250930_1210'),
    ]

    operations = [
    ]
