# Generated by Django 5.1.5 on 2025-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0002_eightpairsswedishformat_fourpairsswedishformat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='signal_recipient_group_ids',
            field=models.TextField(blank=True, help_text='Comma-separated group IDs (e.g., group.ABC123==). Leave empty to use global settings.'),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='signal_recipient_usernames',
            field=models.TextField(blank=True, help_text='Comma-separated phone numbers (e.g., +358401234567, +358409876543). Leave empty to use global settings.'),
        ),
    ]
