# Generated by Django 5.1.5 on 2025-10-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0003_add_per_tournament_signal_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='backend_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.notificationbackendsetting'),
        ),
    ]
