# Generated by Django 5.1.5 on 2025-04-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0004_player_ranking_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='EightPairsSwedishFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='FourPairsSwedishFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='MonarchOfTheCourt8',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_points_sum', models.FloatField()),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_player1', to='tournament_creator.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_player2', to='tournament_creator.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.pair')),
            ],
        ),
        migrations.DeleteModel(
            name='KingOfTheCourt8Players',
        ),
        migrations.AddField(
            model_name='tournamentarchetype',
            name='tournament_category',
            field=models.CharField(choices=[('PAIRS', 'Pairs'), ('MOC', 'Monarch of the Court')], default='PAIRS', max_length=12),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='pair1_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair1_player1_matchups', to='tournament_creator.player'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='pair1_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair1_player2_matchups', to='tournament_creator.player'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='pair2_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair2_player1_matchups', to='tournament_creator.player'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='pair2_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair2_player2_matchups', to='tournament_creator.player'),
        ),
        migrations.AlterField(
            model_name='tournamentchart',
            name='players',
            field=models.ManyToManyField(blank=True, through='tournament_creator.TournamentPlayer', to='tournament_creator.player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='pair1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_pair1', to='tournament_creator.pair'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='pair2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_pair2', to='tournament_creator.pair'),
        ),
        migrations.AddField(
            model_name='tournamentpair',
            name='tournament_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.tournamentchart'),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='pairs',
            field=models.ManyToManyField(blank=True, through='tournament_creator.TournamentPair', to='tournament_creator.pair'),
        ),
    ]
