# Generated by Django 5.1.5 on 2025-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0004_allow_null_backend_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='name_display_format',
            field=models.CharField(choices=[('FIRST', 'First names (with last name initial if needed)'), ('LAST', 'Last names only')], default='FIRST', help_text='How to display player names in notifications and tournament view', max_length=10),
        ),
    ]
