# Generated by Django 5.1.5 on 2025-10-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0005_add_name_display_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='show_structure',
            field=models.BooleanField(default=False, help_text='Show tournament structure in a separate block'),
        ),
        migrations.AlterField(
            model_name='tournamentchart',
            name='name_display_format',
            field=models.CharField(choices=[('FIRST', 'First names'), ('LAST', 'Last names')], default='FIRST', help_text='How to display player names in notifications and tournament view', max_length=10),
        ),
    ]
