# Generated by Django 5.1.5 on 2025-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0006_add_show_structure_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentarchetype',
            name='notes',
            field=models.TextField(blank=True, help_text='Explain the tournament structure and idiosyncrasies'),
        ),
    ]
