# Generated by Django 5.1.5 on 2025-10-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0008_populate_default_archetype_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournament_creator.tournamentarchetype'),
        ),
    ]
