# Generated by Django 5.1.5 on 2025-10-06 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0009_add_archetype_to_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='FivePairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='NinePairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='SevenPairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='SixPairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='TenPairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='ThreePairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='TwoPairsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.AddField(
            model_name='pair',
            name='entry_order',
            field=models.IntegerField(blank=True, help_text='Order in which this pair was entered (1-based)', null=True),
        ),
    ]
