# Generated by Django 5.1.5 on 2025-10-06 03:53

from django.db import migrations


def create_pairs_archetypes(apps, schema_editor):
    """Create archetype instances for all pairs tournament formats (2-10 teams)."""
    TournamentArchetype = apps.get_model('tournament_creator', 'TournamentArchetype')

    pairs_archetypes = [
        {
            'name': '2 pairs doubles tournament',
            'description': 'Best-of-5 format: 1 match with 2 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '3 pairs doubles tournament',
            'description': 'Round robin: 3 rounds on 1 court with 3 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '5 pairs doubles tournament',
            'description': 'Round robin: 5 rounds on 2 courts with 5 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '6 pairs doubles tournament',
            'description': 'Round robin: 5 rounds on 3 courts with 6 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '7 pairs doubles tournament',
            'description': 'Round robin: 7 rounds on 3 courts with 7 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '9 pairs doubles tournament',
            'description': 'Round robin: 9 rounds on 4 courts with 9 pairs.',
            'tournament_category': 'PAIRS'
        },
        {
            'name': '10 pairs doubles tournament',
            'description': 'Round robin: 9 rounds on 5 courts with 10 pairs.',
            'tournament_category': 'PAIRS'
        },
    ]

    for archetype_data in pairs_archetypes:
        TournamentArchetype.objects.get_or_create(**archetype_data)


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0010_add_entry_order_to_pair'),
    ]

    operations = [
        migrations.RunPython(create_pairs_archetypes, reverse_code=migrations.RunPython.noop),
    ]
