# Generated by Django 5.1.5 on 2025-10-06 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0011_populate_pairs_archetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('total_point_difference', models.IntegerField(default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.pair')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.tournamentchart')),
            ],
            options={
                'ordering': ['-wins', '-total_point_difference'],
                'unique_together': {('tournament', 'pair')},
            },
        ),
    ]
