# Generated by Django 5.2.1 on 2025-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0011_notificationbackendsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='notify_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='notify_by_matrix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='notify_by_signal',
            field=models.BooleanField(default=False),
        ),
    ]
