# Generated by Django 5.2.1 on 2025-05-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0011_notificationbackendsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournament_creator.tournamentarchetype'),
        ),
    ]
