# Generated by Django 5.1.5 on 2025-10-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0012_add_pairscore_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['stage__stage_number', 'round_number', 'court_number']},
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(help_text='Order of this stage (1-based)')),
                ('stage_type', models.CharField(choices=[('POOL', 'Pool Play'), ('PLAYOFF', 'Playoff/Finals'), ('ROUND_ROBIN', 'Round Robin')], default='POOL', max_length=20)),
                ('name', models.CharField(help_text="Display name for this stage (e.g., 'Stage 1', 'Pool A', 'Finals')", max_length=100)),
                ('scoring_mode', models.CharField(choices=[('CUMULATIVE', 'Cumulative - Scores carry over from previous stages'), ('RESET', 'Reset - Scores start fresh for this stage')], default='CUMULATIVE', max_length=20)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament_creator.tournamentchart')),
            ],
            options={
                'ordering': ['tournament', 'stage_number'],
                'unique_together': {('tournament', 'stage_number')},
            },
        ),
        migrations.AddField(
            model_name='matchup',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournament_creator.stage'),
        ),
    ]
