# Generated by Django 5.1.5 on 2025-07-22 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0012_tournamentchart_notify_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTiebreakResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_order', models.JSONField()),
                ('wins_tied_at', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tied_players', models.ManyToManyField(to='tournament_creator.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.tournamentchart')),
            ],
            options={
                'ordering': ['-resolved_at'],
                'unique_together': {('tournament', 'wins_tied_at')},
            },
        ),
    ]
