# Generated by Django 5.1.5 on 2025-10-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0013_add_stage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='number_of_stages',
            field=models.IntegerField(default=1, help_text='Number of stages in this tournament (1 for single-stage, 2+ for multi-stage)'),
        ),
    ]
