# Generated by Django 5.1.5 on 2025-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0014_add_number_of_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day tournaments. Leave blank for single-day tournaments.', null=True),
        ),
    ]
