# Generated by Django 5.1.5 on 2025-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0015_add_end_date_to_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='match_date',
            field=models.DateField(blank=True, help_text='For league-format tournaments, the date this match will be played', null=True),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='format_type',
            field=models.CharField(choices=[('STANDARD', 'Standard (round/court based)'), ('LEAGUE', 'League (date-based matches)')], default='STANDARD', help_text='How matches are organized - by round/court or by date', max_length=20),
        ),
    ]
