# Generated by Django 5.1.5 on 2025-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0016_matchup_match_date_tournamentchart_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional nickname to display instead of first name', max_length=255, null=True),
        ),
    ]
