# Generated by Django 5.1.5 on 2025-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0017_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='match_time',
            field=models.TimeField(blank=True, help_text='For league-format tournaments, the time this match will be played', null=True),
        ),
    ]
