# Generated by Django 5.2.13 on 2026-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0018_add_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='default_sets_per_match',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2, help_text='MoC only: typical sets played per match. Used to scale the free win awarded to seeds 1 & 2 in formats where their pairing is eliminated.'),
        ),
    ]
