# Generated by Django 5.2.13 on 2026-07-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0019_tournamentchart_default_sets_per_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='EurosFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this pool (e.g., 'Pool A', 'Places 9-12')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display/processing order of this pool within its stage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournament_creator.stage')),
            ],
            options={
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.AddField(
            model_name='matchup',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournament_creator.pool'),
        ),
        migrations.CreateModel(
            name='PoolPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Pool-internal seed position (1-based)')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.pair')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_creator.pool')),
            ],
            options={
                'ordering': ['pool', 'position'],
                'unique_together': {('pool', 'position')},
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='pairs',
            field=models.ManyToManyField(blank=True, related_name='pools', through='tournament_creator.PoolPair', to='tournament_creator.pair'),
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('stage', 'order')},
        ),
    ]
