# Generated by Django 5.2.13 on 2026-07-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0021_populate_euros_archetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPoolTiebreakResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins_tied_at', models.IntegerField()),
                ('resolved_order', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak_resolutions', to='tournament_creator.pool')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resolved_at'],
                'unique_together': {('pool', 'wins_tied_at')},
            },
        ),
    ]
