# Generated by Django 5.2.13 on 2026-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0022_manualpooltiebreakresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived tournaments are hidden from the normal list and only visible to admins (e.g. tournaments that were never finished properly).'),
        ),
    ]
