# Generated by Django 5.2.13 on 2026-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0025_seed_unranked_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text="Practice tournament: results don't count, any logged-in user can record and reset scores, and no notifications are sent."),
        ),
    ]
