# Generated by Django 5.2.13 on 2026-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0026_tournamentchart_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='short_name',
            field=models.CharField(blank=True, help_text="Short tag used in notifications (e.g. 'EO26'). Falls back to the full name when blank.", max_length=32),
        ),
    ]
