# Generated by Django 5.2.13 on 2026-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0027_tournamentchart_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='label',
            field=models.CharField(blank=True, default='', help_text="Human-readable stakes of a bracket match (e.g. 'Semifinal', 'Final', 'Bronze match', 'Places 5–6'); blank for ordinary round-robin matches, which display by round/court instead", max_length=50),
        ),
    ]
