# Generated by Django 5.2.13 on 2026-07-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0028_matchup_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='country',
            field=models.CharField(default='', help_text="Country the tournament is played in (e.g. 'Finland').", max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this tournament. Has director rights over it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='place',
            field=models.CharField(default='', help_text="Town or city the tournament is played in (e.g. 'Helsinki').", max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TC', 'Tournament Creator'), ('PLAYER', 'Player'), ('SPECTATOR', 'Spectator')], default='SPECTATOR', max_length=10),
        ),
        migrations.CreateModel(
            name='TournamentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors_added', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_roles', to='tournament_creator.tournamentchart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_tournaments', through='tournament_creator.TournamentDirector', through_fields=('tournament', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
