# Generated by Django 5.2.13 on 2026-09-23 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0030_backfill_tournament_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleRoundRobinFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.CreateModel(
            name='RoundRobinPlayoffsFormat',
            fields=[
                ('tournamentarchetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournament_creator.tournamentarchetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('tournament_creator.tournamentarchetype',),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='match_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Pairs only: expected score format per match type (round_robin, semifinal, bronze, final).'),
        ),
    ]
