# Generated by Django 5.2.13 on 2026-09-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0032_populate_multi_phase_pairs_archetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='signup_category',
            field=models.CharField(blank=True, choices=[('MOC', 'Monarch of the Court'), ('PAIRS', 'Doubles (Pairs)')], help_text="Sign-up tournaments only: MoC or doubles (the archetype isn't known until sign-up closes).", max_length=12),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='signup_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='signup_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Most entries accepted; sign-up closes when it's full.", null=True),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='signup_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fewest entries (players for MoC, pairs for doubles) the tournament is played with.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='signup_pairs_format',
            field=models.CharField(blank=True, help_text='Sign-up doubles only: the chosen playing format (PAIRS_FORMAT_OPTIONS key); blank picks by pair count.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='uses_signup',
            field=models.BooleanField(default=False, help_text='Entrants sign up themselves instead of being picked at creation.'),
        ),
        migrations.CreateModel(
            name='TournamentSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_signups', to='tournament_creator.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='tournament_creator.player')),
                ('signed_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_signups', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='tournament_creator.tournamentchart')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
