# Generated by Django 5.2.13 on 2026-09-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_creator', '0033_tournament_signups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchart',
            name='league_avoid_parallel',
            field=models.BooleanField(default=False, help_text='Sign-up leagues: play on one court whenever possible, keeping the others free (e.g. for pickup games).'),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='league_back_to_back',
            field=models.BooleanField(default=True, help_text='Sign-up leagues: players may play in two consecutive time slots.'),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='league_courts',
            field=models.PositiveSmallIntegerField(default=2, help_text='Sign-up leagues: courts in use at the same time.'),
        ),
        migrations.AddField(
            model_name='tournamentchart',
            name='league_max_matches_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sign-up leagues: most matches a player plays in a day; blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentsignup',
            name='partner_times_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentsignup',
            name='player_times_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeagueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_slots', to='tournament_creator.tournamentchart')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('tournament', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='LeagueAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_availabilities', to='tournament_creator.player')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tournament_creator.tournamentsignup')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tournament_creator.leagueslot')),
            ],
            options={
                'unique_together': {('player', 'slot')},
            },
        ),
    ]
